
# How often the check is run to see if a block is under the villager to see if it needs to be ignored (in seconds)
block-check: 10

# What block the villager needs to be standing on to be ignored
disable-block: 'EMERALD_BLOCK'

