name: AntiVillagerLag
version: '1.0-SNAPSHOT'
main: rebelmythik.antivillagerlag.AntiVillagerLag
api-version: 1.18
description: Helps with villager path finding

commands:
  avlreload:
    description: reloads the config

permissions:
  avl.reload:
    description: Allows user to reload the config
  avl.restockcooldown.bypass:
    description: Allows the player to bypass the restock on renaming villagers
  avl.renamecooldown.bypass:
    description: Allows the player to bypass the cooldown on renaming villagers
  avl.message.nextrestock:
    description: Tells the player when the villager is restocking next