name: AntiVillagerLag
version: '1.0-SNAPSHOT'
main: rebelmythik.antivillagerlag.AntiVillagerLag
api-version: 1.18
description: Helps with villager path finding

commands:
  avlreload:
    description: reloads the config

permissions:
  avl.reload:
    description: Allows user to reload the config